spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://***/***?characterEncoding=utf8
    username: root
    password: lyw19990812
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    prefix: classpath:/templates/

server:
  port: 8081
  servlet:
    context-path: /wgcloud

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl